/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/eye.glb
Author: TrentPierce (https://sketchfab.com/TrentPierce)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/eyeball-photorealistic-5c4565daf20e488fad8e0e4335c5c60a
Title: Eyeball - Photorealistic
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/eye.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.12}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Object_4.geometry} material={materials.Scalera} />
            <mesh geometry={nodes.Object_5.geometry} material={materials.Cornea} />
          </group>
          <mesh geometry={nodes.Object_7.geometry} material={materials.Iris} position={[0, 0, -0.11]} rotation={[Math.PI / 2, 0, 0]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/eye.glb')
