/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/eyescene.glb
Author: studio lab (https://sketchfab.com/leonlabyk)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/eyeball-edfdbf89074f49228cd4f2e3ed584578
Title: Eyeball
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations, Sky, Cloud } from '@react-three/drei'
import { Canvas } from '@react-three/fiber'
import {OrbitControls} from '@react-three/drei'



export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/eyescene.glb')
  const { actions, names } = useAnimations(animations, group)
  console.log(names)

    
useEffect (() => {

  actions[names[0]].reset().fadeIn(0.5).play()
}, [actions, names])
  
return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="e92b04216adf4e829d14cc91fa0745c3fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.04}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <group name="Cornea" scale={1.04}>
                    <mesh name="Cornea_CorneaShader_0" geometry={nodes.Cornea_CorneaShader_0.geometry} material={materials.CorneaShader} />
                  </group>
                  <group name="Iris" scale={2.5} />
                  <group name="Sclera" scale={1.04}>
                    <mesh name="Sclera_ScleraEyeShader_0" geometry={nodes.Sclera_ScleraEyeShader_0.geometry} material={materials.ScleraEyeShader} />
                  </group>
                  <skinnedMesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.PupilShader} skeleton={nodes.Object_6.skeleton} />
                  <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.IrisShader} skeleton={nodes.Object_7.skeleton} />
                  <skinnedMesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.LensShader} skeleton={nodes.Object_8.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/eyescene.glb')

export default function Eyescene(props) {
  return (
    <Canvas frameloop="demand"  >
    <ambientLight intensity={0.5} />
    <spotLight position={[1, 15, 10]} angle={0.3} penumbra={1} />
    <pointLight position={[10, 10, 10]} />
    <Sky theme='night' sunPosition={[0, 1, 0]} inclination={0} azimuth={0.25} />
    <Cloud position={[1, 15, 10]}   />
    <OrbitControls />
    
    <Model   {...props} />

 

  </Canvas>
  )
}


